url=https://stagelogistics.brainbees.com/login
browser=chrome
URL_2=https://www.google.com/
driverProperty=webdriver.chrome.driver
driverPath=/home/shubham.jogdand@firstcry.io/Downloads/chromedriver
ExcelSheetName=sheet1
log4JPropertiesFileLoc=/home/shubham.jogdand@firstcry.io/eclipse-workspace/BDD_FrameWork/src/com/projectName/repository/Log44J.properties
maximizeWindow=driver.manage().window().maximize();
implicitWait=driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);


