# Define root logger
log4j.rootLogger=INFO, CONSOLE, HTML

# =========================
# Appenders
# =========================

# Console Appender
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender

# HTML File Appender
log4j.appender.HTML=org.apache.log4j.FileAppender
log4j.appender.HTML.File=./log/log_report.html
log4j.appender.HTML.Append=true

# =========================
# Layouts & Patterns
# =========================

# Console Layout
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n

# HTML Layout
log4j.appender.HTML.layout=org.apache.log4j.HTMLLayout
log4j.appender.HTML.layout.Title=Automation Execution Log
log4j.appender.HTML.layout.LocationInfo=true
